[fix] Error: Unexpected keyword argument 'use_beam_search'
root cause: The new version of VLLM won't support this param any more.
solution: Delete this param

Change-Id: Ife1e6935708ee5f6eb0f8799e73f3979c19568a4
Signed-off-by: Liu_Tianhua <tianhua.liu@metax-tech.com>